// <auto-generated />
using System;
using CoinService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CoinService.Migrations
{
    [DbContext(typeof(CoinsDbContext))]
    [Migration("20210813212252_AddInvoiceIdAndDate")]
    partial class AddInvoiceIdAndDate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("CoinService.Models.User", b =>
                {
                    b.Property<string>("OwnerId")
                        .HasColumnType("text");

                    b.Property<int>("Coins")
                        .HasColumnType("integer");

                    b.Property<string>("InvoiceId")
                        .HasColumnType("text");

                    b.Property<bool>("IsPartner")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("MadePremiumAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("OwnerId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
